// <auto-generated />
namespace w03b.Migrations.AddressMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WORKYOUB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WORKYOUB));
        
        string IMigrationMetadata.Id
        {
            get { return "201701310026512_WORKYOUB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
